events { worker_connections 1024; }
http {
  include /etc/nginx/mime.types;
  server_tokens off;
  log_format minimal '$time_iso8601 $request_method $status $request_time';
  access_log /dev/stdout minimal;
  server {
    listen 80;
    root /app/public;
    client_max_body_size 64k;
    location / { try_files $uri $uri/ /index.php?$query_string; }
    location = /index.php { include fastcgi_params; fastcgi_param SCRIPT_FILENAME /app/public/index.php; fastcgi_param HTTPS $http_x_forwarded_proto; fastcgi_pass app:9000; }
    location ~ \.php$ { return 404; }
    location ~ /\. { deny all; }
  }
}
