ALTER TABLE orders ADD COLUMN receipt_email VARCHAR(254);
ALTER TABLE orders ADD COLUMN receipt_enabled INTEGER NOT NULL DEFAULT 0;
ALTER TABLE orders ADD COLUMN vat_code INTEGER NOT NULL DEFAULT 1;
ALTER TABLE orders ADD COLUMN tax_system INTEGER;
CREATE TABLE advisory_leases (name VARCHAR(50) PRIMARY KEY, token VARCHAR(32) NOT NULL, expires_at BIGINT NOT NULL);
