default: &default
  adapter: postgresql
  encoding: unicode
  url: <%= ENV.fetch("DATABASE_URL", nil) %>
  database: <%= ENV.fetch("DATABASE_NAME", "zeleboba") %>
  username: <%= ENV.fetch("DATABASE_USER", "") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "") %>
  host: <%= ENV.fetch("DATABASE_HOST", "127.0.0.1") %>
  port: <%= ENV.fetch("DATABASE_PORT", "5432") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default

test:
  adapter: sqlite3
  database: ":memory:"

production:
  <<: *default
