\i /docker-entrypoint-initdb.d/migrations/001_initial.sql
\i /docker-entrypoint-initdb.d/migrations/002_operations.sql
\i /docker-entrypoint-initdb.d/migrations/003_security.sql
\i /docker-entrypoint-initdb.d/migrations/004_payment_delivery.sql
\i /docker-entrypoint-initdb.d/migrations/005_checkout_snapshot.sql
\i /docker-entrypoint-initdb.d/migrations/006_freekassa.sql
\i /docker-entrypoint-initdb.d/migrations/007_autorenew.sql
\i /docker-entrypoint-initdb.d/migrations/008_wallet.sql
\i /docker-entrypoint-initdb.d/migrations/009_promocodes.sql
\i /docker-entrypoint-initdb.d/migrations/010_referrals.sql
\i /docker-entrypoint-initdb.d/migrations/011_gifts.sql
\i /docker-entrypoint-initdb.d/migrations/012_trials.sql
\i /docker-entrypoint-initdb.d/migrations/013_marketing.sql
\i /docker-entrypoint-initdb.d/migrations/014_admin_ops.sql
\i /docker-entrypoint-initdb.d/migrations/015_compensations.sql
\i /docker-entrypoint-initdb.d/migrations/015_freekassa_nonce.sql
\i /docker-entrypoint-initdb.d/migrations/016_password_resets.sql
\i /docker-entrypoint-initdb.d/migrations/017_outbox_priority.sql
\i /docker-entrypoint-initdb.d/migrations/018_referral_processing.sql
\i /docker-entrypoint-initdb.d/migrations/019_customer_timeline.sql
