source "https://rubygems.org"

ruby ">= 3.3.0"

gem "rails", "~> 8.1"
gem "pg", "~> 1.5"
gem "puma", "~> 6.4"
gem "bootsnap", "~> 1.18", require: false
gem "argon2", "~> 2.3"
gem "rbnacl", "~> 7.1"

group :development, :test do
  gem "sqlite3", "~> 2.0"
end
