<?php
declare(strict_types=1);
namespace App;
use App\Infrastructure\{Database,Outbox,Worker};
use App\Billing\{BillingService,Wallet,TopupService,CartService,AutoPurchaseService,PromoCodeService,ReferralService,GiftService,TrialService,BroadcastService,ChannelService,LandingService,ContestService,PollService,CampaignService,RbacService,ReportingService,MonitoringService,BackupService,MaintenanceService,UserAdminService,CompensationService,CustomerTimeline};
use App\Identity\{Auth,TelegramLogin,Mfa};
use App\Settings\{Settings,Vault,Branding};
use App\Integration\{Payments,DemoProvisioner,RemnawaveProvisioner,Telegram,PaymentService,Mailer};
use App\Integration\Payment\{ProviderRegistry,CryptoBotProvider,TelegramStarsProvider,LavaProvider,WataProvider,HeleketProvider,PlategaProvider,TributeProvider,YooKassaProvider,FreeKassaProvider,MulenPayProvider,Pal24Provider,CloudPaymentsProvider,KassaAiProvider,RioPayProvider,SeverPayProvider,PayPearProvider,RollyPayProvider,OverpayProvider,AuraPayProvider,EtoplatezhiProvider,AntilopayProvider,JupiterProvider,DonutProvider,CisPayProvider,TabPayProvider,ParityPayProvider};
use App\Payments\PaymentEventStore;
use App\Observability\OperationsService;
use Symfony\Component\HttpClient\HttpClient;
final class Container
{
    public readonly Database $db;
    public readonly Outbox $outbox;
    public readonly BillingService $billing;
    public readonly Wallet $wallet;
    public readonly TopupService $topups;
    public readonly CartService $carts;
    public readonly AutoPurchaseService $autoPurchase;
    public readonly PromoCodeService $promocodes;
    public readonly ReferralService $referrals;
    public readonly GiftService $gifts;
    public readonly TrialService $trials;
    public readonly BroadcastService $broadcasts;
    public readonly ChannelService $channels;
    public readonly LandingService $landings;
    public readonly ContestService $contests;
    public readonly PollService $polls;
    public readonly CampaignService $campaigns;
    public readonly RbacService $rbac;
    public readonly ReportingService $reporting;
    public readonly MonitoringService $monitoring;
    public readonly BackupService $backups;
    public readonly MaintenanceService $maintenance;
    public readonly UserAdminService $userAdmin;
    public readonly CompensationService $compensations;
    public readonly CustomerTimeline $timeline;
    public readonly Payments $payments;
    public readonly PaymentService $paymentService;
    public readonly Mailer $mailer;
    public readonly ProviderRegistry $providers;
    public readonly Worker $worker;
    public readonly Auth $auth;
    public readonly Telegram $telegram;
    public readonly TelegramLogin $telegramLogin;
    public readonly Mfa $mfa;
    public readonly Settings $settings;
    public readonly Branding $branding;
    public readonly OperationsService $operations;
    public readonly array $config;
    public function __construct(array $config)
    {
        $this->db=new Database($config['DATABASE_DSN'],$config['DATABASE_USER']??'',$config['DATABASE_PASSWORD']??'');
        $this->settings=new Settings($this->db,new Vault(dirname(__DIR__).'/var/master.key'));
        $this->config=$config=array_merge(Settings::DEFAULTS,$config,$this->settings->overrides());
        $this->branding=new Branding($config);
        if (!in_array($config['APP_ENV'],['dev','test','prod'],true)) throw new \RuntimeException('Invalid APP_ENV');
        if (!in_array($config['PAYMENT_DRIVER'],['demo','yookassa','freekassa'],true) || !in_array($config['PROVISION_DRIVER'],['demo','remnawave'],true)) throw new \RuntimeException('Unknown integration driver');
        if ($config['APP_ENV']==='prod' && (!$this->db->postgres() || !str_starts_with($config['APP_URL'],'https://'))) throw new \RuntimeException('Production requires PostgreSQL and HTTPS');
        $this->outbox=new Outbox($this->db,$this->settings->vault);
        $this->operations=new OperationsService($this->db);
        $this->timeline=new CustomerTimeline($this->db);
        $this->billing=new BillingService($this->db,$this->outbox,$config['PAYMENT_DRIVER'],$config,$this->timeline);
        $this->wallet=new Wallet($this->db);
        $this->carts=new CartService($this->db);
        $this->topups=new TopupService($this->db,$this->outbox,$this->wallet,$config['PAYMENT_DRIVER'],$config);
        $this->billing->setTopups($this->topups);
        $this->promocodes=new PromoCodeService($this->db,$this->outbox,$this->wallet);
        $this->referrals=new ReferralService($this->db,$this->outbox,$this->wallet,$config);
        $this->gifts=new GiftService($this->db,$this->outbox,$this->wallet,$config);
        $this->autoPurchase=new AutoPurchaseService($this->db,$this->outbox,$this->wallet,$this->carts,$this->billing,$this->gifts);
        $this->trials=new TrialService($this->db,$this->outbox,$this->wallet,$config);
        $this->broadcasts=new BroadcastService($this->db,$this->outbox);
        $this->channels=new ChannelService($this->db,$this->outbox);
        $this->landings=new LandingService($this->db,$this->outbox);
        $this->contests=new ContestService($this->db,$this->outbox,$this->wallet);
        $this->polls=new PollService($this->db,$this->outbox,$this->wallet);
        $this->campaigns=new CampaignService($this->db,$this->outbox,$this->wallet);
        $this->rbac=new RbacService($this->db);
        $this->reporting=new ReportingService($this->db);
        $this->monitoring=new MonitoringService($this->db);
        $this->backups=new BackupService($this->db,dirname(__DIR__).'/var/backups');
        $this->maintenance=new MaintenanceService($this->db);
        $this->compensations=new CompensationService($this->db,$this->outbox,$this->wallet);
        $http=HttpClient::create();
        $this->payments=new Payments($this->db,$this->billing,$http,$config);
        $remnawave=new RemnawaveProvisioner($http,$config['REMNAWAVE_URL'],$config['REMNAWAVE_TOKEN'],$config['REMNAWAVE_SQUAD_UUID']);
        $this->userAdmin=new UserAdminService($this->db,$this->wallet,$config['PROVISION_DRIVER']==='remnawave'?$remnawave:null,$this->outbox,$this->timeline);
        $this->providers=new ProviderRegistry($http,$config);
        foreach ([new YooKassaProvider($http,$config),new FreeKassaProvider($http,$config,$this->db),new CryptoBotProvider($http,$config),new TelegramStarsProvider($http,$config),new LavaProvider($http,$config),new WataProvider($http,$config),new HeleketProvider($http,$config),new PlategaProvider($http,$config),new TributeProvider($http,$config),new MulenPayProvider($http,$config),new Pal24Provider($http,$config),new CloudPaymentsProvider($http,$config),new KassaAiProvider($http,$config),new RioPayProvider($http,$config),new SeverPayProvider($http,$config),new PayPearProvider($http,$config),new RollyPayProvider($http,$config),new OverpayProvider($http,$config),new AuraPayProvider($http,$config),new EtoplatezhiProvider($http,$config),new AntilopayProvider($http,$config),new JupiterProvider($http,$config),new DonutProvider($http,$config),new CisPayProvider($http,$config),new TabPayProvider($http,$config),new ParityPayProvider($http,$config)] as $provider) $this->providers->register($provider);
        $this->paymentService=new PaymentService($this->db,$this->billing,$http,$config,$this->providers,new PaymentEventStore($this->db));
        $this->mailer=new Mailer($this->db,$config);
        $tgBase=rtrim($config['TELEGRAM_API_BASE']??'https://astracattg.netlify.app','/');
        if ($tgBase==='') $tgBase='https://astracattg.netlify.app';
        $this->worker=new Worker($this->db,$this->outbox,$this->payments,new RemnawaveProvisioner($http,$config['REMNAWAVE_URL'],$config['REMNAWAVE_TOKEN'],$config['REMNAWAVE_SQUAD_UUID']),$http,$config['TELEGRAM_BOT_TOKEN'],$config['APP_ENV']!=='prod',$tgBase,$this->topups,$this->autoPurchase,$this->paymentService,$this->referrals,$this->broadcasts,$this->compensations,$config['PROVISION_DRIVER'],$this->timeline);
        $this->auth=new Auth($this->db);$this->mfa=new Mfa($this->db,$this->settings->vault);
        $this->telegramLogin=new TelegramLogin($this->db,$this->auth);
        $this->telegram=new Telegram($this->db,$this->outbox,$this->billing,$config['APP_URL'],$this->telegramLogin,$tgBase,$http);
        $this->telegram->setApp($this);
    }
}
